import './globals.css'
import type { Metadata } from 'next'
import { Inter, Rajdhani } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})
const rajdhani = Rajdhani({
  subsets: ['latin'], weight: '700',
  variable: '--font-rajdhani'
})

export const metadata: Metadata = {
  title: "It's Time ToDo",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${rajdhani.variable}`}>
      <body className='bg-gray-900'>
        {children}
      </body>
    </html>
  )
}
